import { Clock3, Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import { PageHero } from "@/components/common/page-hero";
import { ButtonLink } from "@/components/common/button";
import { ContactForm } from "@/components/forms/contact-form";
import { Reveal } from "@/components/motion/reveal";
import { business, displayBusiness } from "@/config/business";
import { pageMetadata } from "@/config/seo";
import { whatsappUrl } from "@/config/site";

export const metadata=pageMetadata("Contact Paw District","Contact Paw District about grooming, daycare, boarding, wellness, membership or a future visit","/contact");
const info=[[Phone,"Phone",displayBusiness.phone,business.phone?`tel:${business.phone}`:"/contact"],[MessageCircle,"WhatsApp",business.whatsapp?"Start a chat":"Number coming soon",whatsappUrl()],[Mail,"Email",displayBusiness.email,business.email?`mailto:${business.email}`:"/contact"],[Clock3,"Opening hours",displayBusiness.hours.join(" · "),"#hours"]] as const;
export default function ContactPage(){return <><PageHero eyebrow="Come say hello" title="Sniffing optional." copy="Tell us what your pet needs, ask the very specific question, or simply start planning a first visit." breadcrumbs={[{label:"Contact"}]} accent="bg-peach"/><section className="container-shell pb-20 md:pb-28"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><Reveal><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1">{info.map(([Icon,label,value,href])=><a key={label} href={href} className="rounded-3xl border border-ink/10 p-5 transition hover:bg-mint"><Icon className="h-5 w-5 text-forest"/><p className="mt-6 text-[10px] font-extrabold uppercase tracking-[.15em] text-muted">{label}</p><p className="mt-1 font-bold">{value}</p></a>)}</div></Reveal><Reveal delay={.1}><ContactForm/></Reveal></div></section><section id="location" className="container-shell pb-20 md:pb-28"><div className="grid overflow-hidden rounded-5xl bg-cream lg:grid-cols-2"><div className="flex min-h-[380px] items-center justify-center paw-grid"><div className="max-w-sm p-8 text-center"><MapPin className="mx-auto h-10 w-10 text-forest"/><h2 className="mt-5 text-3xl font-bold tracking-[-.04em]">The District map goes here.</h2><p className="mt-4 leading-7 text-muted">Add the real address and coordinates in <code className="rounded bg-white px-1.5 py-1 text-xs">src/config/business.ts</code> before embedding directions.</p></div></div><div className="flex flex-col justify-center p-8 md:p-12"><p className="eyebrow">Visit</p><h2 className="headline">Come find<br/>our corner.</h2><p className="body-lg mt-6">{displayBusiness.address}</p><div id="hours" className="mt-7"><p className="label">Opening hours</p>{displayBusiness.hours.map(item=><p key={item} className="text-muted">{item}</p>)}</div><ButtonLink href={business.latitude?`https://maps.google.com/?q=${business.latitude},${business.longitude}`:"/contact"} className="mt-8 self-start">Get directions</ButtonLink></div></div></section></>}
