import { CheckCircle2 } from "lucide-react";
import { PageHero } from "@/components/common/page-hero";
import { Reveal } from "@/components/motion/reveal";
import { CTASection } from "@/components/sections/cta-section";
import { pageMetadata } from "@/config/seo";

export const metadata = pageMetadata("Why Paw District", "Discover the pet-first standards behind Paw District, from thoughtful routines and clear updates to clean, familiar spaces", "/why-paw-district");
const items=[["We begin with behaviour","A wag does not always mean yes. A pause does not always mean no. We observe before we act."],["Routines are useful data","Meal timing, sleep habits, sensitivities and comfort cues help us make the day feel more familiar."],["Cleanliness is a system","It lives in tools, surfaces, handovers, laundry and the rhythm of the whole day."],["We say when something is not right","Good care includes honest limits, veterinary referrals and recommending a different environment when needed."],["Updates have a purpose","You should know how they ate, played, rested and felt—not just receive a polished photo."],["Familiarity reduces friction","One team across services means fewer introductions and more remembered details."]];
export default function WhyPage(){return <><PageHero eyebrow="The difference" title="Good care starts with noticing the small things." copy="Authority does not need loud claims. It lives in thoughtful questions, clean routines and the confidence to slow down." breadcrumbs={[{label:"Why Paw District"}]} accent="bg-mint" /><section className="container-shell section-pad"><div className="grid gap-5 md:grid-cols-2">{items.map(([title,copy],index)=><Reveal key={title} delay={(index%2)*.06} className="rounded-4xl border border-ink/10 p-7 md:p-10"><CheckCircle2 className="h-7 w-7 text-forest"/><h2 className="mt-12 text-3xl font-bold tracking-[-.05em]">{title}</h2><p className="mt-4 max-w-xl leading-7 text-muted">{copy}</p></Reveal>)}</div></section><CTASection /></>}
