import { Check } from "lucide-react";
import { PageHero } from "@/components/common/page-hero";
import { ButtonLink } from "@/components/common/button";
import { FAQAccordion } from "@/components/common/faq-accordion";
import { Reveal } from "@/components/motion/reveal";
import { CTASection } from "@/components/sections/cta-section";
import { pageMetadata } from "@/config/seo";
import { membershipPlans } from "@/data/membership";

export const metadata=pageMetadata("Pet Care Membership","Explore editable Paw District membership plans for regular grooming, daycare benefits and preferred booking requests","/membership");
const faqs=[{question:"Are these final plans and prices?",answer:"No. The plans, benefits and pricing structure are clearly marked as placeholders until Paw District approves the real membership offer."},{question:"Will membership guarantee a slot?",answer:"The final booking rules are still to be confirmed. Membership should not be presented as a guaranteed booking unless the operating policy supports that promise."},{question:"Can I use benefits across pets?",answer:"This will depend on the approved membership terms. Ask the team when real plan details are published."}];
export default function MembershipPage(){return <><PageHero eyebrow="For the regulars" title="For pets who practically have their own seat here." copy="A simpler rhythm for grooming, play days and everyday care—with benefits that feel useful, not noisy." breadcrumbs={[{label:"Membership"}]} accent="bg-peach" /><section className="container-shell section-pad"><p className="mb-8 rounded-2xl bg-sun/45 p-4 text-center text-xs font-bold uppercase tracking-[.12em] text-amber-900">Development placeholders · all prices and benefits need business approval</p><div className="grid gap-6 lg:grid-cols-3">{membershipPlans.map((plan,index)=><Reveal key={plan.name} delay={index*.07} className={`relative flex flex-col rounded-5xl border p-7 md:p-9 ${plan.featured?"border-forest bg-forest text-white shadow-soft":"border-ink/10 bg-white"}`}>{plan.featured&&<span className="absolute right-6 top-6 rounded-full bg-sun px-3 py-1 text-[9px] font-extrabold uppercase tracking-widest text-ink">Sample popular</span>}<p className={`text-[10px] font-extrabold uppercase tracking-[.18em] ${plan.featured?"text-mint":"text-forest"}`}>{plan.name}</p><p className="mt-8 text-3xl font-bold tracking-[-.05em]">{plan.price}</p><p className={`mt-4 leading-7 ${plan.featured?"text-white/65":"text-muted"}`}>{plan.description}</p><ul className={`my-8 space-y-4 border-y py-8 ${plan.featured?"border-white/15":"border-ink/10"}`}>{plan.features.map(item=><li key={item} className="flex gap-3 text-sm font-semibold"><Check className={`h-4 w-4 shrink-0 ${plan.featured?"text-sun":"text-forest"}`}/>{item}</li>)}</ul><ButtonLink href="/contact" variant={plan.featured?"light":"primary"} className="mt-auto">Ask about this plan</ButtonLink></Reveal>)}</div></section><section className="container-shell pb-20 md:pb-28"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><Reveal><p className="eyebrow">Membership FAQs</p><h2 className="headline">Worth knowing.</h2></Reveal><Reveal delay={.1}><FAQAccordion items={faqs}/></Reveal></div></section><CTASection title="Build a care rhythm that fits." copy="Ask about regular visits now, and we will share the approved membership details when they are ready."/></>}
