"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { CheckCircle2, LoaderCircle } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { submitLead } from "@/lib/forms/submit-lead";

const schema=z.object({name:z.string().min(2,"Tell us your name."),phone:z.string().min(8,"Add a phone number we can reach."),email:z.string().email("Use a valid email address."),petName:z.string().min(1,"What should we call your pet?"),petType:z.enum(["Dog","Cat","Other"],{message:"Choose a pet type."}),service:z.string().min(1,"Choose an area."),message:z.string().min(10,"A little more detail will help us respond well.")});
type Values=z.infer<typeof schema>;
export function EnquiryForm(){const[success,setSuccess]=useState<string|null>(null);const[submitError,setSubmitError]=useState("");const{register,handleSubmit,formState:{errors,isSubmitting},reset}=useForm<Values>({resolver:zodResolver(schema),defaultValues:{petType:"Dog",service:""}});const onSubmit=async(values:Values)=>{setSubmitError("");const result=await submitLead({type:"enquiry",...values});if(result.ok){setSuccess(result.reference);reset();}else setSubmitError(result.message);};if(success)return <div className="rounded-4xl bg-mint p-8 text-center md:p-12" role="status"><CheckCircle2 className="mx-auto h-10 w-10 text-forest"/><h2 className="mt-5 text-3xl font-bold tracking-[-.04em]">Message received. Tail wag pending.</h2><p className="mt-3 text-muted">Development reference: {success}. This demo does not send data to a real inbox yet.</p><button className="btn-primary mt-7" onClick={()=>setSuccess(null)}>Send another message</button></div>;return <form onSubmit={handleSubmit(onSubmit)} noValidate className="card p-6 md:p-9"><div className="grid gap-5 sm:grid-cols-2"><Field label="Your name" error={errors.name?.message}><input className="field" {...register("name")} autoComplete="name"/></Field><Field label="Phone" error={errors.phone?.message}><input className="field" {...register("phone")} type="tel" autoComplete="tel"/></Field><Field label="Email" error={errors.email?.message}><input className="field" {...register("email")} type="email" autoComplete="email"/></Field><Field label="Pet name" error={errors.petName?.message}><input className="field" {...register("petName")}/></Field><Field label="Pet type" error={errors.petType?.message}><select className="field" {...register("petType")}><option>Dog</option><option>Cat</option><option>Other</option></select></Field><Field label="Interested in" error={errors.service?.message}><select className="field" {...register("service")}><option value="">Choose an area</option><option>Boarding</option><option>Grooming</option><option>Training</option><option>Membership</option><option>Something else</option></select></Field></div><div className="mt-5"><Field label="How can we help?" error={errors.message?.message}><textarea className="field min-h-36 resize-y" {...register("message")}/></Field></div>{submitError&&<p className="error mt-4" role="alert">{submitError}</p>}<button className="btn-primary mt-6" disabled={isSubmitting}>{isSubmitting?<><LoaderCircle className="h-4 w-4 animate-spin"/>Sending</>:"Send to the District"}</button><p className="mt-4 text-xs leading-5 text-muted">Development mode: validation and success states work; delivery integrations are intentionally not connected.</p></form>}

function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label><span className="label">{label}</span>{children}{error&&<span className="error" role="alert">{error}</span>}</label>}
